apiVersion: v1
kind: ServiceAccount
metadata:
  name: fct-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fc-labeler
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fct-rbac
subjects:
  - kind: ServiceAccount
    name: fct-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: fc-labeler
  apiGroup: rbac.authorization.k8s.io
