apiVersion: apps/v1
kind: Deployment
metadata:
  name: fct-deployment
  labels:
    app: fct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fct
  template:
    metadata:
      labels:
        app: fct
    spec:
      containers:
        - name: fct
          image: idoko/fct:0.1
      serviceAccountName: fct-sa
